"""add consultation requests table

Revision ID: 1382244a48e0
Revises: bdd30460bf8a
Create Date: 2026-07-24 16:07:37.537092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1382244a48e0'
down_revision: Union[str, Sequence[str], None] = 'bdd30460bf8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('consultation_type', sa.Enum('ADDICTION', 'CONSTIPATION', name='consultationtype'), nullable=False),
    sa.Column('summary_data', sa.Text(), nullable=False),
    sa.Column('tracking_code', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultation_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultation_requests_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultation_requests_tracking_code'), ['tracking_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultation_requests_tracking_code'))
        batch_op.drop_index(batch_op.f('ix_consultation_requests_phone_number'))
        batch_op.drop_index(batch_op.f('ix_consultation_requests_id'))

    op.drop_table('consultation_requests')
    # ### end Alembic commands ###
