"""clean duplicate columns

Revision ID: 2ec3a6296239
Revises: 1eaf24a6e725
Create Date: 2026-08-13 14:11:31.180349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec3a6296239'
down_revision: Union[str, Sequence[str], None] = '1eaf24a6e725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_wallets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_doctor_wallets_doctor_id'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_wallets', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_doctor_wallets_doctor_id'), ['doctor_id'])

    # ### end Alembic commands ###
