"""add doctor wallet and billing tables

Revision ID: 532bfefdcb6d
Revises: ef6469a0f850
Create Date: 2026-08-18 14:18:11.142089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532bfefdcb6d'
down_revision: Union[str, Sequence[str], None] = 'ef6469a0f850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_verifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_verifications_phone'), ['phone'], unique=False)

    with op.batch_alter_table('consultation_requests', schema=None) as batch_op:
        batch_op.alter_column('consultation_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ADDICTION', 'CONSTIPATION', name='consultationtype'),
               existing_nullable=False)

    with op.batch_alter_table('doctor_wallet_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_wallet_transactions_id'), ['id'], unique=False)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'IRR'"), nullable=False))

    with op.batch_alter_table('doctor_wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_wallet_transactions_id'))

    with op.batch_alter_table('consultation_requests', schema=None) as batch_op:
        batch_op.alter_column('consultation_type',
               existing_type=sa.Enum('ADDICTION', 'CONSTIPATION', name='consultationtype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_verifications_phone'))
        batch_op.drop_index(batch_op.f('ix_otp_verifications_id'))

    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
