"""remove_unique_constraint_from_availability_id

Revision ID: 862413c4e7d5
Revises: c4a8e2f17b91
Create Date: 2026-07-23 09:43:49.263139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862413c4e7d5'
down_revision: Union[str, Sequence[str], None] = 'c4a8e2f17b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
