"""add wallet status columns

Revision ID: 8c1abb8ed1e8
Revises: add_missing_doctor_wallet_columns
Create Date: 2026-08-13 13:11:46.362933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1abb8ed1e8'
down_revision: Union[str, Sequence[str], None] = 'add_missing_doctor_wallet_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
