"""add wallet and transactions tables

Revision ID: c43091e1aeb8
Revises: f8d3c1a9e03c
Create Date: 2026-08-08 16:43:47.270868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43091e1aeb8'
down_revision: Union[str, Sequence[str], None] = 'f8d3c1a9e03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ایجاد جداول جدید کیف پول و تراکنش
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_wallets_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_wallets')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallets_user_id'), ['user_id'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_wallet_id', sa.Integer(), nullable=True),
    sa.Column('receiver_wallet_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAW', 'TRANSFER', 'REFUND', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('tracking_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='fk_transactions_appointment_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_wallet_id'], ['wallets.id'], name='fk_transactions_receiver_wallet_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['wallets.id'], name='fk_transactions_sender_wallet_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_transactions')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tracking_code'), ['tracking_code'], unique=True)

    # اصلاح: حذف مستقیم جدول بدون تلاش برای حذف ایندکس‌هایی که شاید وجود نداشته باشند
    op.execute("DROP TABLE IF EXISTS otp_verifications")

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('medical_council_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('specialty_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('waiting_time_estimate',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_doctors_user_id'), ['user_id'], unique=True)

        # در SQLite برای حذف و ایجاد مجدد FK حتما باید نام مشخص باشد
        try:
            batch_op.drop_constraint('fk_doctors_specialty_id', type_='foreignkey')
        except:
            pass
        batch_op.create_foreign_key('fk_doctors_specialty_id', 'specialties', ['specialty_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        try:
            batch_op.drop_index(batch_op.f('ix_specialties_name'))
        except:
            pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_name'), ['name'], unique=1)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_doctors_specialty_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_doctors_specialty_id', 'specialties', ['specialty_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_doctors_user_id'))
        batch_op.alter_column('waiting_time_estimate',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('bio',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('province',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('specialty_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('medical_council_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('otp_verifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=11), nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_otp_verifications')
    )
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_verifications_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_verifications_id'), ['id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_tracking_code'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallets_id'))

    op.drop_table('wallets')
    # ### end Alembic commands ###
