"""fix doctor specialty relation

Revision ID: d15f0f6be5b4
Revises: 862413c4e7d5
Create Date: 2026-07-23 16:22:03.192879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15f0f6be5b4'
down_revision: Union[str, Sequence[str], None] = '862413c4e7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_specialties_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_specialties_slug'), ['slug'], unique=True)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty_id', sa.Integer(), nullable=False))
        # تغییر مهم: نام گذاری صریح کلید خارجی به 'fk_doctors_specialty_id'
        batch_op.create_foreign_key('fk_doctors_specialty_id', 'specialties', ['specialty_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=120), nullable=False))
        # تغییر مهم: مشخص کردن نام دقیق کلید خارجی برای حذف در زمان برگشت به عقب
        batch_op.drop_constraint('fk_doctors_specialty_id', type_='foreignkey')
        batch_op.drop_column('specialty_id')

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialties_slug'))
        batch_op.drop_index(batch_op.f('ix_specialties_name'))
        batch_op.drop_index(batch_op.f('ix_specialties_id'))

    op.drop_table('specialties')
    # ### end Alembic commands ###
