"""add is_active and transaction fields

Revision ID: d83bf872b3f9
Revises: 84dadbaf28ac
Create Date: 2026-08-10 16:44:24.359704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83bf872b3f9'
down_revision: Union[str, Sequence[str], None] = '84dadbaf28ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_wallet_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_doctor_wallet_transactions_reference_id'), ['reference_id'], unique=False)

    with op.batch_alter_table('doctor_wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_wallets', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('doctor_wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_wallet_transactions_reference_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('description')
        batch_op.drop_column('reference_id')

    # ### end Alembic commands ###
